const KEY="mithraExpenseData";const defaultData={expenses:[],salary:[],emi:[],loan:[],settings:{currency:"₹",theme:"dark"}};let data=JSON.parse(localStorage.getItem(KEY)||"null")||defaultData;
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function money(n){return (data.settings.currency||"₹")+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}
function today(){return new Date().toISOString().slice(0,10)}
function currentMonth(){return new Date().toISOString().slice(0,7)}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function openModal(id){$( "#"+id).classList.add("show");const f=$("#"+id+" form");if(f&&f.elements.date&&!f.elements.date.value)f.elements.date.value=today();if(f&&f.elements.month&&!f.elements.month.value)f.elements.month.value=currentMonth()}
function closeModal(id){$("#"+id).classList.remove("show")}
$$(".nav-btn").forEach(b=>b.onclick=()=>go(b.dataset.page));
$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
function go(page){$$(".page").forEach(x=>x.classList.remove("active-page"));$("#"+page).classList.add("active-page");$$(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("#pageTitle").textContent=page==="dashboard"?"Mithra Expenses Tracker":page[0].toUpperCase()+page.slice(1)}
function saveExpense(e){e.preventDefault();const f=new FormData(e.target);data.expenses.unshift({id:Date.now(),title:f.get("title"),amount:+f.get("amount"),date:f.get("date"),category:f.get("category"),method:f.get("method")});e.target.reset();closeModal("expenseModal");save()}
function saveSalary(e){e.preventDefault();const f=new FormData(e.target);data.salary.unshift({id:Date.now(),month:f.get("month"),amount:+f.get("amount"),note:f.get("note")});e.target.reset();closeModal("salaryModal");save()}
function saveEmi(e){e.preventDefault();const f=new FormData(e.target);data.emi.unshift({id:Date.now(),name:f.get("name"),amount:+f.get("amount"),due:f.get("due"),total:+f.get("total"),paid:+f.get("paid")});e.target.reset();closeModal("emiModal");save()}
function saveLoan(e){e.preventDefault();const f=new FormData(e.target);data.loan.unshift({id:Date.now(),name:f.get("name"),amount:+f.get("amount"),paid:+f.get("paid"),date:f.get("date"),due:f.get("due")});e.target.reset();closeModal("loanModal");save()}
function remove(type,id){data[type]=data[type].filter(x=>x.id!==id);save()}
function renderExpenses(){const q=($("#expenseSearch")?.value||"").toLowerCase(),m=$("#expenseMonth")?.value||"";let a=data.expenses.filter(x=>(!q||x.title.toLowerCase().includes(q)||x.category.toLowerCase().includes(q))&&(!m||x.date.startsWith(m)));$("#expenseTable").innerHTML=a.length?a.map(x=>`<div class="data-row"><div><b>${esc(x.title)}</b><div class="muted">${esc(x.category)} • ${esc(x.method||"")}</div></div><div>${x.date}</div><div class="amount">${money(x.amount)}</div><div></div><button class="delete" onclick="remove('expenses',${x.id})">Delete</button></div>`).join(""):`<div class="empty">No expenses yet.</div>`}
function renderSalary(){$("#salaryTable").innerHTML=data.salary.length?data.salary.map(x=>`<div class="data-row"><div><b>${x.month}</b><div class="muted">${esc(x.note||"")}</div></div><div class="amount">${money(x.amount)}</div><div></div><div></div><button class="delete" onclick="remove('salary',${x.id})">Delete</button></div>`).join(""):`<div class="empty">No salary records yet.</div>`}
function renderEmi(){$("#emiTable").innerHTML=data.emi.length?data.emi.map(x=>{let rem=Math.max(0,x.total-x.paid);return `<div class="data-row"><div><b>${esc(x.name)}</b><div class="muted">Due ${x.due} • ${rem} remaining</div></div><div class="amount">${money(x.amount)}/month</div><div>${x.paid}/${x.total} paid</div><div>${rem?'<span class="muted">Pending</span>':'<b>Completed</b>'}</div><button class="delete" onclick="remove('emi',${x.id})">Delete</button></div>`}).join(""):`<div class="empty">No EMI records yet.</div>`}
function renderLoan(){$("#loanTable").innerHTML=data.loan.length?data.loan.map(x=>{let rem=Math.max(0,x.amount-x.paid);return `<div class="data-row"><div><b>${esc(x.name)}</b><div class="muted">Borrowed ${x.date}${x.due?" • Due "+x.due:""}</div></div><div>${money(x.amount)} total</div><div>${money(x.paid)} paid</div><div class="amount">${money(rem)} remaining</div><button class="delete" onclick="remove('loan',${x.id})">Delete</button></div>`}).join(""):`<div class="empty">No loan records yet.</div>`}
function renderDashboard(){let m=currentMonth(),inc=data.salary.filter(x=>x.month===m).reduce((s,x)=>s+x.amount,0),exp=data.expenses.filter(x=>x.date.startsWith(m)).reduce((s,x)=>s+x.amount,0);$("#income").textContent=money(inc);$("#expense").textContent=money(exp);$("#savings").textContent=money(inc-exp);$("#balance").textContent=money(inc-exp);$("#monthLabel").textContent=m;let cats={};data.expenses.filter(x=>x.date.startsWith(m)).forEach(x=>cats[x.category]=(cats[x.category]||0)+x.amount);let max=Math.max(1,...Object.values(cats));$("#categoryBars").innerHTML=Object.keys(cats).length?Object.entries(cats).map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><b>${money(v)}</b></div>`).join(""):`<div class="empty">No expenses this month.</div>`;$("#recentExpenses").innerHTML=data.expenses.slice(0,5).map(x=>`<div class="data-row"><div><b>${esc(x.title)}</b><div class="muted">${esc(x.category)}</div></div><div>${x.date}</div><div class="amount">${money(x.amount)}</div><div></div></div>`).join("")||`<div class="empty">No recent expenses.</div>`;let upcoming=data.emi.filter(x=>x.paid<x.total).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,3);$("#upcomingEmi").innerHTML=upcoming.map(x=>`<div class="data-row"><div><b>${esc(x.name)}</b><div class="muted">${x.due}</div></div><div class="amount">${money(x.amount)}</div></div>`).join("")||`<div class="empty">No pending EMI.</div>`}
function renderReports(){let er=data.expenses.reduce((s,x)=>s+x.amount,0),si=data.salary.reduce((s,x)=>s+x.amount,0),lr=data.loan.reduce((s,x)=>s+(x.amount-x.paid),0);$("#reportSummary").innerHTML=`<h3>Overall Summary</h3><p class="muted">Total income: <b>${money(si)}</b> • Total expenses: <b>${money(er)}</b> • Loan remaining: <b>${money(lr)}</b></p>`}
function renderAll(){renderDashboard();renderExpenses();renderSalary();renderEmi();renderLoan();renderReports();$("#currency").value=data.settings.currency;$("#themeSelect").value=data.settings.theme;document.body.classList.toggle("light",data.settings.theme==="light")}
function csv(rows){return rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\n")}
function downloadCSV(type){let a=data[type],rows=[Object.keys(a[0]||{id:"",name:"",amount:""}),...a.map(x=>Object.values(x))];let blob=new Blob([csv(rows)],{type:"text/csv"}),u=URL.createObjectURL(blob),l=document.createElement("a");l.href=u;l.download=`mithra-${type}-report.csv`;l.click();URL.revokeObjectURL(u)}
function downloadAll(){let blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),l=document.createElement("a");l.href=u;l.download="mithra-backup.json";l.click();URL.revokeObjectURL(u)}
function clearData(){if(confirm("Clear all Mithra data?")){data=structuredClone(defaultData);save()}}
$("#themeBtn").onclick=()=>{data.settings.theme=data.settings.theme==="dark"?"light":"dark";save()}
$("#themeSelect").onchange=e=>{data.settings.theme=e.target.value;save()}
$("#currency").onchange=e=>{data.settings.currency=e.target.value;save()}
$("#expenseSearch").oninput=renderExpenses;$("#expenseMonth").oninput=renderExpenses;
renderAll();